### ISSUE TITLE
Add Explanation for username and password

### ISSUE THREAD

**Issue by mmiillii** [weltmeyer/python_sonnenbatterie#1]
Hi, I was wondering where you did get the username and password for the sonnenbatterie to obtain data from the other endpoints beside v1/status which works without username and password. 
Did you need to configure something on the Sonnen Dashboard? 
Thanks for sharing your insights
-Max

EDIT: 
Just came across the discussion here which provides some insights 
https://community.home-assistant.io/t/custom-integration-sonnenbatterie/181781/15

**Comment by weltmeyer** [comment]
Hi,
username and password should be in you documents. but just in case you dont find it you can try:
username: User
password: sonnenUser3552

**Comment by mmiillii** [comment]
That actually did work for me
